name: Playwright Tests

on:
  workflow_dispatch:
  
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
    
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
      
      - name: Install CI dependencies
        run: |
          cp package.ci.json package.json
          npm install --package-lock=false --no-audit --prefer-offline
      
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Auth Setup - Create Storage State
        run: npm run pw:setup
      
      - name: Run Playwright tests - Login Functionality
        run: npm run pw:login

      - name: Run Playwright tests - Signup Functionality
        run: npm run pw:signup
      
      - name: Run Playwright tests - Footer Functionality
        run: npm run pw:footer

      - name: Run Playwright tests - end-to-end scenario
        run: npm run pw:scenario
      
      - name: Upload Playwright Test Results
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: playwright-test-results
          path: test-results/
          retention-days: 7
        
      - name: Restore Allure History
        if: always()
        run: |
          git clone --depth=1 --branch gh-pages https://github.com/${{ github.repository }} gh-pages || true

          if [ -d "gh-pages/history" ]; then
            mkdir -p results/playwright/test-results/allure-results/history
            cp -r gh-pages/history/* results/playwright/test-results/allure-results/history/
          fi
          
      - name: Debug - Check allure binary
        if: always()
        run: |
          ls -la node_modules/allure-commandline/dist/ 2>/dev/null || echo "Allure CLI dist folder missing!"
          npx allure --version
            - name: Generate Allure Report
              if: always()
              run: |
                npx allure generate results/playwright/test-results/allure-results --clean -o results/playwright/test-results/allure-report

      - name: Deploy Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./results/playwright/test-results/allure-report

